name: action
run-name: running docker container
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build and run in Docker container
        run: docker build -t solver ${{github.workspace}}
      - name: Run tests
        run: docker run -v ${{github.workspace}}/logs:/home/logs solver
      - name: Check container
        run: cat ${{github.workspace}}/logs/log.txt

